### ISSUE TITLE
Research on mechanisms to digitally store songs

### ISSUE THREAD

**Issue by ykakarap** [WeibelLab-Teaching/CSE218_Fa19_Sayam#25]
Come up with a "structure" on how to store the key information of the selected song.

The structure should contain the following information:
- What key needs to be pressed in a frame - Will need to figure out how to relate real time stamp to a frame
- What finger needs to be used to press the key
- When to show the press and when to hide the press
- (Optional) Should be able to adjust to variable speed (tempo)

**Comment by AkshanshChahal** [comment]
Trying to import MIDI files using a C# library

**Comment by SabrinaSimao** [comment]
Using NAudio library in Unity (it can read .mid files and get the notes)
Trying to open file and read it. Also, tried to copy the data on a float array and send to debug log.
Got a bunch of null pointer errors -> heeelp

**Comment by SabrinaSimao** [comment]
Basically we will use pre made files first. If we need, we will convert them with python. In the end, if everything is beautiful, we come back to this.
